README.md
I have updated the game name to show the team name also. It will show up as Vipers' Rattle Battle. I have also updated the description of the game.
=> Update README with team name

client/.eslintrc.json, client/package.json, client/yarn.lock
=> Fix eslint config client

client/package.json, client/src/components/Navbar.js, client/src/components/__tests__/Navbar.test.js, client/yarn.lock
=> Add Navbar

client/.eslintrc.json, client/src/App.test.js, client/src/components/__tests__/Navbar.test.js, client/src/setupTests.js
=> Move Enzyme Adapter configuration to setupTests.js

server/.eslintrc.json, server/fake-test.test.js, server/jest.config.js, server/package.json
=> Add test script on server

.travis.yml, package.json
=> Add CI using travis

README.md, client/README.md, server/README.md
=> docs: Add setup instructions on README.md

server/Controllers/GameControllers/snake.js, server/__tests__/snake.test.js
This code implements the initial properties of a Snake class, by defining the constructor parameters.
=> [RFC]: Implements initial state of a snake

server/.babelrc, server/__tests__/index.test.js, server/package.json, server/src/app/app.js, server/src/index.js, server/src/routes/routes.js, server/yarn.lock
Babel support has been added in the server folder. Now ES6 modules and features can be used. resolves #33
=> Add Babel to server

client/.env.example, client/package.json, client/src/config/environment.js, client/src/config/socketIO.js, client/yarn.lock
=> setup socket on client

client/src/App.js, client/src/App.test.js, client/src/components/AuthButtons.js, client/src/components/FormDialog.js, client/src/components/Navbar.js, client/src/components/RequiredFormTextField.js, client/src/components/SignupModal.js, client/src/components/__tests__/AuthButtons.test.js, client/src/components/__tests__/FormDialog.test.js, client/src/components/__tests__/Navbar.test.js, client/src/components/__tests__/RequiredFormTextField.test.js, client/src/components/__tests__/SignupModal.test.js, client/src/customHooks/useFormTextField.js, client/src/customHooks/useSignupForm.js
=> Sign Up Component

client/package.json, client/src/components/CheckBoxWithLabel.js, client/src/components/FormDialog.js, client/src/components/LoginModal.js, client/src/components/Navbar.js, client/src/components/__tests__/CheckBoxWithLabel.test.js, client/src/components/__tests__/FormDialog.test.js, client/src/components/__tests__/LoginModal.test.js, client/src/components/__tests__/Navbar.test.js, client/src/components/__tests__/SignupModal.test.js, client/src/components/__tests__/testUtils.js, client/src/customHooks/useCheckBox.js, client/src/customHooks/useLoginForm.js
=> Login component

client/src/customHooks/__tests__/testUtils.js, client/src/customHooks/__tests__/useCheckBox.test.js, client/src/customHooks/__tests__/useFormTextField.test.js, client/src/customHooks/__tests__/useLoginForm.test.js, client/src/customHooks/__tests__/useSignupForm.test.js
=> Tests for custom hooks

server/Controllers/GameControllers/gameConstants.js, server/Controllers/GameControllers/snake.js, server/Controllers/GameControllers/tempCodeRunnerFile.js, server/__tests__/snake.test.js
In this feature implementation, I have implemented the snake movement function, while handling the events when the snake eats food, collides with itself, or collides with a rival.
=> [RFM]: feat: Implement snake unit movement mechanics.

.gitignore, client/.eslintrc.json, client/package.json, client/src/App.js, client/src/App.test.js, client/src/components/AuthButtons.js, client/src/components/LoginModal.js, client/src/components/LogoutButton.js, client/src/components/Navbar.js, client/src/components/SignupAndLoginButtons.js, client/src/components/SignupModal.js, client/src/components/__tests__/AuthButtons.test.js, client/src/components/__tests__/LoginModal.test.js, client/src/components/__tests__/LogoutButton.test.js, client/src/components/__tests__/Navbar.test.js, client/src/components/__tests__/SignupModal.test.js, client/src/components/__tests__/testUtils.js, client/src/customHooks/__tests__/handleFormErrors.test.js, client/src/customHooks/__tests__/handleFormSuccess.test.js, client/src/customHooks/__tests__/useSignupForm.test.js, client/src/customHooks/handleFormErrors.js, client/src/customHooks/handleFormSuccess.js, client/src/customHooks/useSignupForm.js, client/src/utils/__tests__/auth-api.test.js, client/src/utils/__tests__/fetch-api.test.js, client/src/utils/auth-api.js, client/src/utils/fetch-api.js, client/src/utils/user-context.js, client/yarn.lock
=> Attach APIs to Signup Form

client/src/components/LoginModal.js, client/src/components/__tests__/LoginModal.test.js, client/src/customHooks/__tests__/useLoginForm.test.js, client/src/customHooks/useLoginForm.js
=> Attach APIs to Login Form

package.json, yarn.lock
Doing `yarn start:dev` on the root now starts both client and server in dev mode!
=> chore: Add start script in main package.json

client/src/components/Home.js, client/src/components/Leaderboard.js, client/src/components/MaterialTable.js, client/src/components/__tests__/Leaderboard.test.js, client/src/utils/__mocks__/leaderboard-api.js, client/src/utils/__mocks__/mockUtils.js, client/src/utils/leaderboard-api.js
React component for leaderboards has been added.
=> Add Leaderboard component

server/__tests__/game.test.js, server/src/controllers/GameControllers/game.js, server/src/controllers/GameControllers/snake.js, server/src/controllers/GameControllers/tempCodeRunnerFile.js, server/src/controllers/GameControllers/utility.js, server/src/database/connection.js, server/src/index.js, server/yarn.lock
Some refactoring that this code refactoring includes:-
- Changed parameters to a function into one single object.
- Changed switch case to object(it is a great way to shorten the code)
- Fix typos and some other minor changes.
=> Refactor: game engine

client/src/components/Home.js, client/src/components/Scoreboard.js, client/src/components/gameBoardComponent/gameBoardComponent.css, client/src/components/gameBoardComponent/gameBoardComponent.js, client/src/index.css, server/__tests__/snake.test.js, server/src/controllers/GameControllers/game.js, server/src/controllers/GameControllers/snake.js, server/src/index.js
I have added a section on the Game board to show the scores of both the snakes
resolves #87
=> Add scoreboards for each snake

client/src/components/Home.js, client/src/components/LoginPrompt.js
=> feat: show prompt if user is not logged in

client/src/components/gameBoardComponent/gameBoardComponent.js, server/__tests__/snake.test.js, server/src/controllers/GameControllers/game.js, server/src/controllers/GameControllers/snake.js, server/src/index.js
- Implemented game lost alert
- It handles user tab closing
- It handles the intersection of wall and snake
=> feat: implement game lost and wall intersection of snake

client/src/components/Home.js, client/src/components/Scoreboard.js, client/src/components/gameBoardComponent/gameBoardComponent.js, client/src/index.css, server/src/controllers/GameControllers/game.js, server/src/controllers/GameControllers/snake.js, server/src/index.js
The scoreboard now indicates the logged in user
This commit also fixes an issue in Home component that was preventing the game from starting.
=> Add indicator in scoreboard for logged in user

client/src/components/Home.js, client/src/components/gameBoardComponent/gameBoardComponent.js, server/src/controllers/GameControllers/game.js, server/src/index.js
1. Change `games` data structure from array to objects for faster lookups and easier mantainence.
2. handle socket.disconnect event for case when game was started but client disconnected before anyone could join. 
3. fixed a few other bugs in `GameBoardComponent`
4.  Also, minor refactoring just to make codeclimate happy.
=> fix: Game end issues

client/src/components/gameBoardComponent/gameBoardComponent.js
only one player was able to control their snake. fixed it. :)
=> fix: unable to control snakes
